/*
  Warnings:

  - Added the required column `gamePoints` to the `PvpGame` table without a default value. This is not possible if the table is not empty.

*/
-- AlterTable
ALTER TABLE "PvpGame" ADD COLUMN     "gamePoints" DOUBLE PRECISION NOT NULL;

-- AlterTable
ALTER TABLE "Scale" ALTER COLUMN "percoWinPoints" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "percoNDPoints" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "percoLoosePoints" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "prismWinPoints" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "prismNDPoints" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "prismLoosePoints" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "bigPercoWinPoints" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "bigPercoNDPoints" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "bigPercoLoosePoints" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "bigPrismWinPoints" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "bigPrismNDPoints" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "bigPrismLoosePoints" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "avaWin" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "avaLoose" SET DATA TYPE DOUBLE PRECISION;
