name: PVR Back CD

on:
  push:
    branches: [main]
    paths:
      - back/**

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      working-directory: back/
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      NODE_ENV: production

    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --config fly-pvr.toml --env DATABASE_URL=${{ secrets.PVR_DATABASE_URL }} DISCORD_CLIENT_ID=${{ secrets.PVR_DISCORD_CLIENT_ID }} DISCORD_CLIENT_SECRET=${{ secrets.PVR_DISCORD_CLIENT_SECRET }} JWT_SECRET=${{ secrets.PVR_JWT_SECRET }} ORIGIN=${{ secrets.PVR_ORIGIN }} --remote-only
        working-directory: ${{env.working-directory}}
