name: Back CI

on:
  pull_request:
    branches: [main]
    paths:
      - back/**

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: back/

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install
        working-directory: ${{env.working-directory}}

      - name: Build app
        run: npm run build
        working-directory: ${{env.working-directory}}
