name: Bot CI

on:
  pull_request:
    branches: [main]
    paths:
      - bot/**

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: bot/

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.4

      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: ${{env.working-directory}}

      - name: Create env file
        run: |
          echo "BOT=${{secrets.DOMAIN}}" > .env
          echo "API_URL=${{secrets.API_URL}}" >> .env
        working-directory: ${{env.working-directory}}

      - name: Build app
        run: python -m build
        working-directory: ${{env.working-directory}}
