name: Bot CD

on:
  pull_request:
    branches: [main]
    paths:
      - bot/**

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      working-directory: bot/
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      NODE_ENV: production

    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        working-directory: ${{env.working-directory}}
