name: Front CD

on:
  push:
    branches: [main]
    paths:
      - front/*

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: front/

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install
        working-directory: ${{env.working-directory}}

      - name: Build app
        run: npm run build
        working-directory: ${{env.working-directory}}

      - run: ls
        working-directory: ${{env.working-directory}}/public

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: front-artifact
          path: ${{env.working-directory}}/public

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      working-directory: front/
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      NODE_ENV: production

    steps:
      - uses: actions/checkout@v3

      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: front-artifact

      - run: ls

      # - uses: superfly/flyctl-actions/setup-flyctl@master

      # - run: flyctl deploy --remote-only
      #   working-directory: ${{env.working-directory}}
