name: Front CI

on:
  pull_request:
    branches: [main]
    paths:
      - front/*

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: front/

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install
        working-directory: ${{env.working-directory}}

      - name: Create env file
        run: |
          echo "DOMAIN=${{secrets.DOMAIN}}" > .env
          echo "FRONT_CLIENT_ID=${{secrets.FRONT_CLIENT_ID}}" >> .env
          echo "API_URL=${{secrets.API_URL}}" >> .env
          echo "COUNCIL_ROLE_ID=${{secrets.COUNCIL_ROLE_ID}}" >> .env
          echo "AUDIENCE=${{secrets.AUDIENCE}}" >> .env

      - name: Build app
        run: npm run build
        working-directory: ${{env.working-directory}}
