name: Front CI

on:
  pull_request:
    branches: [main]
    paths:
      - front/*

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: front/
      DOMAIN: ${{secrets.DOMAIN}}
      FRONT_CLIENT_ID: ${{secrets.FRONT_CLIENT_ID}}
      API_URL: ${{secrets.API_URL}}
      COUNCIL_ROLE_ID: ${{secrets.COUNCIL_ROLE_ID}}
      AUDIENCE: ${{secrets.AUDIENCE}}

    steps:
      - uses: actions/checkout@v3

      - name: test
        run: echo ${{ env.DOMAIN }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install
        working-directory: ${{env.working-directory}}

      - name: Build app
        run: npm run build
        working-directory: ${{env.working-directory}}
